import { AegisHarnessError, HarnessErrorCodes, ContextRoles, AuthorityDecisions, FailureClasses } from "@aegis/harness-contracts";
export function createExecutionContext(input){const required=["executionId","taskId","harnessId","harnessVersion","authorityRef","provenanceRef"];for(const key of required)if(input[key]===undefined||input[key]==="")throw new AegisHarnessError(HarnessErrorCodes.PROVENANCE_INCOMPLETE,`missing ${key}`);return Object.freeze({...input,toolCalls:0,modelCalls:0,retries:0});}
export function validateContextEntries(entries){for(const entry of entries){if(!entry.sourceRef||!entry.role)throw new AegisHarnessError(HarnessErrorCodes.PROVENANCE_INCOMPLETE,"context source/role missing");if([ContextRoles.DATA,ContextRoles.EVIDENCE,ContextRoles.MEMORY,ContextRoles.TOOL_RESULT].includes(entry.role)&&entry.executableInstructionAllowed)throw new AegisHarnessError(HarnessErrorCodes.CONTEXT_INJECTION,"untrusted context cannot become executable instruction",{entryId:entry.id});}return true;}
export function createAuthorityGuard(policy){return{evaluate(intent,context){const decision=policy(intent,context);if(![AuthorityDecisions.ALLOW,AuthorityDecisions.REQUIRE_APPROVAL,AuthorityDecisions.DENY].includes(decision))throw new Error("invalid authority decision");return decision;}};}
export function createBudgetGuard(limits={}){const usage={toolCalls:0,modelCalls:0,retries:0};function consume(kind){usage[kind]+=1;const max=limits[`max${kind[0].toUpperCase()}${kind.slice(1)}`];if(max!==undefined&&usage[kind]>max)throw new AegisHarnessError(HarnessErrorCodes.BUDGET_EXHAUSTED,`${kind} budget exhausted`,{usage:usage[kind],max});}return{consume,snapshot:()=>({...usage})};}
export function createToolRuntime({contracts,authorityGuard,budgetGuard,trace}){return{async invoke(toolId,input,context){const contract=contracts.get(toolId);if(!contract)throw new AegisHarnessError(HarnessErrorCodes.UNKNOWN_TOOL,`unknown tool ${toolId}`);const decision=authorityGuard.evaluate({type:"TOOL_CALL",toolId,sideEffect:contract.sideEffect},context);if(decision!==AuthorityDecisions.ALLOW)throw new AegisHarnessError(HarnessErrorCodes.AUTHORITY_DENIED,`tool ${toolId} not allowed`,{decision});budgetGuard.consume("toolCalls");trace.push({type:"TOOL_CALL",toolId});try{const value=await contract.execute(input);trace.push({type:"TOOL_RESULT",toolId,status:"SUCCESS"});return{status:"SUCCESS",value,evidenceRefs:[]};}catch(error){const failureClass=error?.code==="ETIMEDOUT"?FailureClasses.TIMEOUT:FailureClasses.UNKNOWN;trace.push({type:"TOOL_RESULT",toolId,status:"FAILURE",failureClass});return{status:"FAILED",error:{message:String(error?.message??error),failureClass},evidenceRefs:[]};}}};}
export async function validateSequence(validators,value,context){const results=[];for(const validator of validators){const result=await validator(value,context);results.push(result);if(!result?.pass)throw new AegisHarnessError(HarnessErrorCodes.VALIDATION_FAILED,result?.reason??"validation failed",{results});}return results;}
export async function retryWithBudget(operation,{maxRetries=0,idempotent=false,budgetGuard}={}){let attempt=0;while(true){try{return await operation(attempt);}catch(error){if(attempt>=maxRetries||!idempotent)throw new AegisHarnessError(HarnessErrorCodes.RETRY_NOT_ALLOWED,"retry denied",{attempt,idempotent,cause:String(error?.message??error)});budgetGuard?.consume("retries");attempt+=1;}}}
export function createTraceCollector(){const events=[];return{push:e=>events.push(Object.freeze({...e})),snapshot:()=>events.map(e=>({...e}))};}
export function createProvenanceCollector(base){const refs={memory:[],knowledge:[],evidence:[],tools:[]};return{add(kind,ref){if(!refs[kind])throw new Error(`unknown provenance kind ${kind}`);refs[kind].push(ref);},finalize(extra={}){const out={...base,...refs,...extra};for(const key of ["taskRef","harnessVersion","policyVersion","provenanceRef"])if(!out[key])throw new AegisHarnessError(HarnessErrorCodes.PROVENANCE_INCOMPLETE,`missing provenance ${key}`);return Object.freeze(out);}};}
export function extractFailureSignature({verifierCause,causalBehavior,reusableMechanism,affectedHarnessSurface,evidenceRefs=[]}){if(!verifierCause||!causalBehavior||!reusableMechanism||!affectedHarnessSurface)throw new AegisHarnessError(HarnessErrorCodes.PROVENANCE_INCOMPLETE,"failure signature incomplete");return Object.freeze({verifierCause,causalBehavior,reusableMechanism,affectedHarnessSurface,evidenceRefs});}
export async function executeHarness({context,contextEntries=[],authorityGuard,toolRuntime,toolRequest,validators=[],provenanceCollector,trace}){validateContextEntries(contextEntries);const decision=authorityGuard.evaluate({type:"EXECUTE_TASK",taskId:context.taskId},context);if(decision!==AuthorityDecisions.ALLOW)throw new AegisHarnessError(HarnessErrorCodes.AUTHORITY_DENIED,"execution not allowed",{decision});trace.push({type:"HARNESS_EXECUTION_STARTED",executionId:context.executionId});let output=null;if(toolRequest)output=await toolRuntime.invoke(toolRequest.toolId,toolRequest.input,context);await validateSequence(validators,output,context);const provenance=provenanceCollector.finalize({outputStatus:output?.status??"NO_TOOL"});trace.push({type:"HARNESS_EXECUTION_COMPLETED",executionId:context.executionId});return{status:"COMPLETED",output,provenance,trace:trace.snapshot()};}
