import test from "node:test";
import assert from "node:assert/strict";
import { MemoryKinds, MemoryStates, AegisMemoryError, MemoryErrorCodes } from "@aegis/memory-contracts";
import { createMemoryItem, workingToEpisode, episodeToCandidateLesson, promoteCandidateToSemantic, createFailureMemory, retractMemory } from "@aegis/memory-runtime";
import { retrieveMinimumContext, buildPointContext } from "@aegis/retrieval-runtime";
const prov={sourceRef:"task-1",sourceType:"PAST_TASK"};
function working(id="w1"){return createMemoryItem({id,kind:MemoryKinds.WORKING,scope:"PROJECT",content:"alpha",key:"alpha",quality:.8,freshness:1,trust:.9,provenance:prov});}
test("working memory requires provenance",()=>assert.throws(()=>createMemoryItem({id:"x",kind:MemoryKinds.WORKING,scope:"PROJECT",content:"x"}),e=>e instanceof AegisMemoryError&&e.code===MemoryErrorCodes.PROVENANCE_REQUIRED));
test("working -> episode requires validation",()=>assert.throws(()=>workingToEpisode(working(),{episodeId:"e1"}),e=>e.code===MemoryErrorCodes.PROMOTION_DENIED));
test("episode -> candidate lesson requires pattern and evidence",()=>{const e=workingToEpisode(working(),{episodeId:"e1",validationRef:"v1"});assert.throws(()=>episodeToCandidateLesson(e,{candidateId:"c1",patternRef:"p1"}),x=>x.code===MemoryErrorCodes.PROMOTION_DENIED);});
test("candidate lesson cannot become semantic without review/generalization evidence",()=>{const e=workingToEpisode(working(),{episodeId:"e1",validationRef:"v1"});const c=episodeToCandidateLesson(e,{candidateId:"c1",patternRef:"p1",evidenceRefs:["ev1"]});assert.equal(c.state,MemoryStates.STAGED);assert.throws(()=>promoteCandidateToSemantic(c,{semanticId:"s1"}),x=>x.code===MemoryErrorCodes.PROMOTION_DENIED);});
test("local/project lesson cannot silently escalate to GLOBAL",()=>{const e=workingToEpisode(working(),{episodeId:"e1",validationRef:"v1"});const c=episodeToCandidateLesson(e,{candidateId:"c1",patternRef:"p1",evidenceRefs:["ev1"]});assert.throws(()=>promoteCandidateToSemantic(c,{semanticId:"s1",reviewRef:"r1",generalizationEvidenceRefs:["g1"],targetScope:"GLOBAL"}),x=>x.code===MemoryErrorCodes.SCOPE_ESCALATION);});
test("validated candidate can become semantic with preserved lineage",()=>{const e=workingToEpisode(working(),{episodeId:"e1",validationRef:"v1"});const c=episodeToCandidateLesson(e,{candidateId:"c1",patternRef:"p1",evidenceRefs:["ev1"]});const s=promoteCandidateToSemantic(c,{semanticId:"s1",reviewRef:"r1",generalizationEvidenceRefs:["g1","g2"],targetScope:"GLOBAL"});assert.equal(s.kind,MemoryKinds.SEMANTIC);assert.equal(s.provenance.derivedFrom,"c1");});
test("failure memory remains a distinct first-class memory type",()=>{const f=createFailureMemory({id:"f1",scope:"PROJECT",content:"timeout mechanism",provenance:{sourceRef:"trace-1",sourceType:"PAST_FAILURE"}});assert.equal(f.kind,MemoryKinds.FAILURE);});
test("retracted memory is excluded from retrieval",()=>{const active=working("a");const retracted=retractMemory(working("b"),{reason:"wrong",decisionRef:"d1"});const r=retrieveMinimumContext([active,retracted],{key:"alpha"},{maxItems:10});assert.deepEqual(r.map(x=>x.item.id),["a"]);});
test("selective retrieval ranks exact before structural/semantic and respects maxItems",()=>{const items=[working("exact"),createMemoryItem({id:"struct",kind:MemoryKinds.EPISODIC,scope:"PROJECT",content:"struct",signature:"sig",quality:1,freshness:1,trust:1,provenance:prov}),createMemoryItem({id:"semantic",kind:MemoryKinds.EPISODIC,scope:"PROJECT",content:"sem",quality:1,freshness:1,trust:1,provenance:prov})];const r=retrieveMinimumContext(items,{key:"alpha",signature:"sig",semanticScore:i=>i.id==="semantic"?1:0},{maxItems:2});assert.deepEqual(r.map(x=>x.item.id),["exact","struct"]);});
test("retrieval filters low-quality and stale items",()=>{const good=working("good");const low=createMemoryItem({id:"low",kind:MemoryKinds.EPISODIC,scope:"PROJECT",content:"low",key:"alpha",quality:.1,freshness:1,provenance:prov});const stale=createMemoryItem({id:"stale",kind:MemoryKinds.EPISODIC,scope:"PROJECT",content:"stale",key:"alpha",quality:1,freshness:.1,provenance:prov});const r=retrieveMinimumContext([good,low,stale],{key:"alpha"},{minQuality:.5,minFreshness:.5,maxItems:10});assert.deepEqual(r.map(x=>x.item.id),["good"]);});
test("point context packages only selected memory, never the whole repository",()=>{const results=retrieveMinimumContext([working("1"),working("2"),working("3"),working("4")],{key:"alpha"},{maxItems:4});const context=buildPointContext(results,{maxItems:2});assert.equal(context.length,2);});
