import test from "node:test";
import assert from "node:assert/strict";
import { validateControlPlane } from "../tools/workstream-collision-check.mjs";
function fixture(){return{ownership:{responsibilities:[{id:"owner-a",owner:"pkg-a"},{id:"owner-b",owner:"pkg-b"}]},domains:{domains:[{id:"domain-a",ownerResponsibilities:["owner-a"]},{id:"domain-b",ownerResponsibilities:["owner-b"]}]},capabilities:{capabilities:[{id:"cap-a",domain:"domain-a",ownerResponsibility:"owner-a"},{id:"cap-b",domain:"domain-b",ownerResponsibility:"owner-b"}]},workstreams:[{id:"ws-a",state:"ACTIVE",ownerResponsibility:"owner-a",capabilityIds:["cap-a"],touchPaths:["a/"]},{id:"ws-ref",state:"REFERENCE",ownerResponsibility:"owner-a",capabilityIds:["cap-a"],touchPaths:["a/"]}]};}
test("reference workstream may overlap active implementation",()=>assert.equal(validateControlPlane(fixture()).activeWorkstreams,1));
test("duplicate capability fails closed",()=>{const d=fixture();d.capabilities.capabilities.push({id:"cap-a",domain:"domain-a",ownerResponsibility:"owner-a"});assert.throws(()=>validateControlPlane(d),/AEGIS-WS-003/);});
test("owner mismatch fails closed",()=>{const d=fixture();d.workstreams[0].ownerResponsibility="owner-b";assert.throws(()=>validateControlPlane(d),/AEGIS-WS-009/);});
test("same active capability fails closed",()=>{const d=fixture();d.workstreams.push({id:"ws-c",state:"ACTIVE_CANDIDATE",ownerResponsibility:"owner-a",capabilityIds:["cap-a"],touchPaths:["c/"]});assert.throws(()=>validateControlPlane(d),/AEGIS-WS-010/);});
test("overlapping active canonical path fails closed",()=>{const d=fixture();d.workstreams.push({id:"ws-c",state:"ACTIVE_CANDIDATE",ownerResponsibility:"owner-b",capabilityIds:["cap-b"],touchPaths:["a/sub/"]});assert.throws(()=>validateControlPlane(d),/AEGIS-WS-011/);});
