export const HarnessErrorCodes = Object.freeze({AUTHORITY_DENIED:"AEGIS-HARNESS-001",CONTEXT_INJECTION:"AEGIS-HARNESS-002",UNKNOWN_TOOL:"AEGIS-HARNESS-003",BUDGET_EXHAUSTED:"AEGIS-HARNESS-004",VALIDATION_FAILED:"AEGIS-HARNESS-005",PROVENANCE_INCOMPLETE:"AEGIS-HARNESS-006",RETRY_NOT_ALLOWED:"AEGIS-HARNESS-007"});
export class AegisHarnessError extends Error { constructor(code,message,details={}) { super(message); this.name="AegisHarnessError"; this.code=code; this.details=details; } }
export const ContextRoles = Object.freeze({POLICY:"POLICY",INSTRUCTION:"INSTRUCTION",DATA:"DATA",EVIDENCE:"EVIDENCE",MEMORY:"MEMORY",TOOL_RESULT:"TOOL_RESULT"});
export const AuthorityDecisions = Object.freeze({ALLOW:"ALLOW",REQUIRE_APPROVAL:"REQUIRE_APPROVAL",DENY:"DENY"});
export const FailureClasses = Object.freeze({TRANSIENT:"TRANSIENT",PERMANENT:"PERMANENT",AUTHORITY:"AUTHORITY",TIMEOUT:"TIMEOUT",INTEGRITY:"INTEGRITY",RESOURCE:"RESOURCE",UNKNOWN:"UNKNOWN"});
