import { AegisMemoryError, MemoryErrorCodes, MemoryKinds, MemoryStates } from "@aegis/memory-contracts";
function assertProvenance(input){if(!input?.provenance?.sourceRef||!input?.provenance?.sourceType)throw new AegisMemoryError(MemoryErrorCodes.PROVENANCE_REQUIRED,"memory provenance required");}
export function createMemoryItem(input){assertProvenance(input);if(!input.id||!input.kind||!input.scope||input.content===undefined)throw new AegisMemoryError(MemoryErrorCodes.INVALID_MEMORY,"memory id/kind/scope/content required");return Object.freeze({state:MemoryStates.ACTIVE,quality:0.5,freshness:1,...input});}
export function workingToEpisode(working,{episodeId,validationRef}){if(working.kind!==MemoryKinds.WORKING)throw new AegisMemoryError(MemoryErrorCodes.INVALID_MEMORY,"working memory required");if(!validationRef)throw new AegisMemoryError(MemoryErrorCodes.PROMOTION_DENIED,"validation required for episode capture");return createMemoryItem({...working,id:episodeId,kind:MemoryKinds.EPISODIC,provenance:{...working.provenance,derivedFrom:working.id,validationRef}});}
export function episodeToCandidateLesson(episode,{candidateId,patternRef,evidenceRefs=[]}){if(episode.kind!==MemoryKinds.EPISODIC)throw new AegisMemoryError(MemoryErrorCodes.INVALID_MEMORY,"episode required");if(!patternRef||evidenceRefs.length===0)throw new AegisMemoryError(MemoryErrorCodes.PROMOTION_DENIED,"pattern and evidence required");return createMemoryItem({...episode,id:candidateId,kind:MemoryKinds.CANDIDATE_LESSON,state:MemoryStates.STAGED,provenance:{...episode.provenance,derivedFrom:episode.id,patternRef,evidenceRefs}});}
export function promoteCandidateToSemantic(candidate,{semanticId,reviewRef,generalizationEvidenceRefs=[],targetScope}){if(candidate.kind!==MemoryKinds.CANDIDATE_LESSON||candidate.state!==MemoryStates.STAGED)throw new AegisMemoryError(MemoryErrorCodes.PROMOTION_DENIED,"staged candidate lesson required");if(!reviewRef||generalizationEvidenceRefs.length===0)throw new AegisMemoryError(MemoryErrorCodes.PROMOTION_DENIED,"review/generalization evidence required");const scope=targetScope??candidate.scope;const order=["TASK","PROJECT","DOMAIN","ORGANIZATION","GLOBAL"];if(order.indexOf(scope)>order.indexOf(candidate.scope)&&generalizationEvidenceRefs.length<2)throw new AegisMemoryError(MemoryErrorCodes.SCOPE_ESCALATION,"scope promotion requires stronger evidence");return createMemoryItem({...candidate,id:semanticId,kind:MemoryKinds.SEMANTIC,scope,state:MemoryStates.ACTIVE,provenance:{...candidate.provenance,derivedFrom:candidate.id,reviewRef,generalizationEvidenceRefs}});}
export function createFailureMemory(input){return createMemoryItem({...input,kind:MemoryKinds.FAILURE});}
export function retractMemory(item,{reason,decisionRef}){if(!reason||!decisionRef)throw new AegisMemoryError(MemoryErrorCodes.INVALID_MEMORY,"retraction reason and decisionRef required");return Object.freeze({...item,state:MemoryStates.RETRACTED,retraction:{reason,decisionRef}});}
export function createInMemoryMemoryRepository(initial=[]){const items=new Map(initial.map(i=>[i.id,i]));return{put(item){items.set(item.id,item);return item;},get(id){return items.get(id)??null;},list(){return [...items.values()];}};}
